export const ipcChannels = {
	window: {
		minimize: "trackboi:window-minimize",
		toggleMaximize: "trackboi:window-toggle-maximize",
		close: "trackboi:window-close",
		startDrag: "trackboi:window-start-drag",
		startResize: "trackboi:window-start-resize",
	},
	trackboi: {
		getActiveProject: "trackboi:get-active-project",
		listProjects: "trackboi:list-projects",
		listView: "trackboi:list-view",
		readDesktopState: "trackboi:read-desktop-state",
		prewarmProjects: "trackboi:prewarm-projects",
		setSelectedWorktree: "trackboi:set-selected-worktree",
		listBoards: "trackboi:list-boards",
		setActiveBoard: "trackboi:set-active-board",
		readAppSettings: "trackboi:read-app-settings",
		updateAppSettings: "trackboi:update-app-settings",
		listDetectedEditors: "trackboi:list-detected-editors",
		openCardInEditor: "trackboi:open-card-in-editor",
		setStorageSearchPaths: "trackboi:set-storage-search-paths",
		setActiveWorkspaceFile: "trackboi:set-active-workspace-file",
		createBoard: "trackboi:create-board",
		deleteBoard: "trackboi:delete-board",
		listTracks: "trackboi:list-tracks",
		getTrack: "trackboi:get-track",
		createTrack: "trackboi:create-track",
		updateTrack: "trackboi:update-track",
		deleteTrack: "trackboi:delete-track",
		readTrackFile: "trackboi:read-track-file",
		writeTrackFile: "trackboi:write-track-file",
		deleteTrackFile: "trackboi:delete-track-file",
		openWorkspaceFile: "trackboi:open-workspace-file",
		chooseProject: "trackboi:choose-project",
		locateProject: "trackboi:locate-project",
		removeProject: "trackboi:remove-project",
		switchProject: "trackboi:switch-project",
		createCard: "trackboi:create-card",
		updateCard: "trackboi:update-card",
		updateBoard: "trackboi:update-board",
		updateProjectPeople: "trackboi:update-project-people",
		addCardComment: "trackboi:add-card-comment",
		moveCard: "trackboi:move-card",
		deleteCard: "trackboi:delete-card",
	},
	events: {
		desktopStorePatch: "trackboi://desktop-store-patch",
	},
} as const;
